//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AbaxXbrl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AbaxXbrl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbaxXBRLCore.lang.AbaxXbrl", typeof(AbaxXbrl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar.
        /// </summary>
        public static string Activar {
            get {
                return ResourceManager.GetString("Activar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Activo {
            get {
                return ResourceManager.GetString("Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido Materno.
        /// </summary>
        public static string ApellidoMaterno {
            get {
                return ResourceManager.GetString("ApellidoMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Apellido Materno del usuario es requerido.
        /// </summary>
        public static string ApellidoMaternoVacio {
            get {
                return ResourceManager.GetString("ApellidoMaternoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido Paterno.
        /// </summary>
        public static string ApellidoPaterno {
            get {
                return ResourceManager.GetString("ApellidoPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Apellido Paterno del usuario es requerido.
        /// </summary>
        public static string ApellidoPaternoVacio {
            get {
                return ResourceManager.GetString("ApellidoPaternoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar.
        /// </summary>
        public static string Aplicar {
            get {
                return ResourceManager.GetString("Aplicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar Emisoras.
        /// </summary>
        public static string AsignarEmisoras {
            get {
                return ResourceManager.GetString("AsignarEmisoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar Emisoras a Usuario.
        /// </summary>
        public static string AsignarEmisorasUsuario {
            get {
                return ResourceManager.GetString("AsignarEmisorasUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar Facultades.
        /// </summary>
        public static string AsignarFacultades {
            get {
                return ResourceManager.GetString("AsignarFacultades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar Facultades a Roles.
        /// </summary>
        public static string AsignarFacultadesRoles {
            get {
                return ResourceManager.GetString("AsignarFacultadesRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar Roles..
        /// </summary>
        public static string AsignarRoles {
            get {
                return ResourceManager.GetString("AsignarRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar Roles a Grupo.
        /// </summary>
        public static string AsignarRolesGrupo {
            get {
                return ResourceManager.GetString("AsignarRolesGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar Usuario.
        /// </summary>
        public static string AsignarUsuario {
            get {
                return ResourceManager.GetString("AsignarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar Usuarios a Grupo.
        /// </summary>
        public static string AsignarUsuariosGrupo {
            get {
                return ResourceManager.GetString("AsignarUsuariosGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitácora.
        /// </summary>
        public static string Bitacora {
            get {
                return ResourceManager.GetString("Bitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloquear.
        /// </summary>
        public static string Bloquear {
            get {
                return ResourceManager.GetString("Bloquear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string Borrar {
            get {
                return ResourceManager.GetString("Borrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Borrado Correctamente.
        /// </summary>
        public static string BorrarGrupo {
            get {
                return ResourceManager.GetString("BorrarGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro de borrar el rol seleccionado?.
        /// </summary>
        public static string BorrarRol {
            get {
                return ResourceManager.GetString("BorrarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE_EXITO_USUARIO_BORRADO.
        /// </summary>
        public static string BorrarUsuario {
            get {
                return ResourceManager.GetString("BorrarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string BotonCancelar {
            get {
                return ResourceManager.GetString("BotonCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string BotonEditar {
            get {
                return ResourceManager.GetString("BotonEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar.
        /// </summary>
        public static string BotonRegistrar {
            get {
                return ResourceManager.GetString("BotonRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        public static string BotonSeleccionar {
            get {
                return ResourceManager.GetString("BotonSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Contraseña.
        /// </summary>
        public static string CambiarContraseña {
            get {
                return ResourceManager.GetString("CambiarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Contraseña.
        /// </summary>
        public static string CambiarPassword {
            get {
                return ResourceManager.GetString("CambiarPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de Grupos.
        /// </summary>
        public static string CatalogoDeGrupos {
            get {
                return ResourceManager.GetString("CatalogoDeGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Sesión.
        /// </summary>
        public static string CerrarSesion {
            get {
                return ResourceManager.GetString("CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea eliminar el Documento de Instancia?.
        /// </summary>
        public static string ConfirmarEliminarDocumento {
            get {
                return ResourceManager.GetString("ConfirmarEliminarDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La constraseña y/o el password son incorrectos.
        /// </summary>
        public static string ConstraseñaPassword {
            get {
                return ResourceManager.GetString("ConstraseñaPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE_WARNING_CONTRASEÑA_ANTERIOR.
        /// </summary>
        public static string ContraselaAnteriorNoCoincide {
            get {
                return ResourceManager.GetString("ContraselaAnteriorNoCoincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha generado y enviado una nueva contraseña.
        /// </summary>
        public static string ContrasenaGenerada {
            get {
                return ResourceManager.GetString("ContrasenaGenerada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE_EXITO_CONTRASEÑA_CAMBIADA.
        /// </summary>
        public static string ContraseñaModificada {
            get {
                return ResourceManager.GetString("ContraseñaModificada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE_WARNING_FORMATO_CONTRASEÑA .
        /// </summary>
        public static string ContraseñaNuevaFormato {
            get {
                return ResourceManager.GetString("ContraseñaNuevaFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE_WARNING_CONTRASEÑA_USADA.
        /// </summary>
        public static string ContraseñaUsada {
            get {
                return ResourceManager.GetString("ContraseñaUsada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electrónico.
        /// </summary>
        public static string Correo {
            get {
                return ResourceManager.GetString("Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Correo Eletrónico del usuario es requerido.
        /// </summary>
        public static string CorreoElectronicoVacio {
            get {
                return ResourceManager.GetString("CorreoElectronicoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Correo no cumple con el formato deseado.
        /// </summary>
        public static string CorreoSinFormato {
            get {
                return ResourceManager.GetString("CorreoSinFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Documento XBRL.
        /// </summary>
        public static string CrearDocumento {
            get {
                return ResourceManager.GetString("CrearDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        public static string De {
            get {
                return ResourceManager.GetString("De", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desbloquear.
        /// </summary>
        public static string Desbloquear {
            get {
                return ResourceManager.GetString("Desbloquear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string DescripcionGrupo {
            get {
                return ResourceManager.GetString("DescripcionGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción del Grupo es requerido.
        /// </summary>
        public static string DescripcionGrupoVacio {
            get {
                return ResourceManager.GetString("DescripcionGrupoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string DescripcionRolEtiqueta {
            get {
                return ResourceManager.GetString("DescripcionRolEtiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string DescripcionRolTabla {
            get {
                return ResourceManager.GetString("DescripcionRolTabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripcion del rol es requerida.
        /// </summary>
        public static string DescripcionRolVacia {
            get {
                return ResourceManager.GetString("DescripcionRolVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorio de Usuarios.
        /// </summary>
        public static string DirectorioUsuarios {
            get {
                return ResourceManager.GetString("DirectorioUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domicilio Fiscal.
        /// </summary>
        public static string DomicilioFiscal {
            get {
                return ResourceManager.GetString("DomicilioFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Grupo.
        /// </summary>
        public static string EditarGrupo {
            get {
                return ResourceManager.GetString("EditarGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Usuario.
        /// </summary>
        public static string EditarUsuario {
            get {
                return ResourceManager.GetString("EditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elegir.
        /// </summary>
        public static string Elegir {
            get {
                return ResourceManager.GetString("Elegir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Empresa.
        /// </summary>
        public static string EliminarEmpresa {
            get {
                return ResourceManager.GetString("EliminarEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Grupo.
        /// </summary>
        public static string EliminarGrupo {
            get {
                return ResourceManager.GetString("EliminarGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Rol.
        /// </summary>
        public static string EliminarRol {
            get {
                return ResourceManager.GetString("EliminarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Usuario.
        /// </summary>
        public static string EliminarUsuario {
            get {
                return ResourceManager.GetString("EliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electrónico.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE_ERROR_AUTENTICAR_USUARIO_SIN_CORREO.
        /// </summary>
        public static string EmailReq {
            get {
                return ResourceManager.GetString("EmailReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emisora.
        /// </summary>
        public static string Emisora {
            get {
                return ResourceManager.GetString("Emisora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emisoras Asignadas..
        /// </summary>
        public static string EmisorasAsignadas {
            get {
                return ResourceManager.GetString("EmisorasAsignadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emisoras Asignadas Correctamente..
        /// </summary>
        public static string EmisorasAsignadasCorrectamente {
            get {
                return ResourceManager.GetString("EmisorasAsignadasCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emisoras Por Asignar..
        /// </summary>
        public static string EmisorasPorASignar {
            get {
                return ResourceManager.GetString("EmisorasPorASignar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa Borrada Correctamente.
        /// </summary>
        public static string EmpresaBorrada {
            get {
                return ResourceManager.GetString("EmpresaBorrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al Borrar la Empresa.
        /// </summary>
        public static string EmpresaErrorBorrar {
            get {
                return ResourceManager.GetString("EmpresaErrorBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al Guardar la Empresa.
        /// </summary>
        public static string EmpresaErrorGuardar {
            get {
                return ResourceManager.GetString("EmpresaErrorGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa Guardada Correctamente.
        /// </summary>
        public static string EmpresaGuardado {
            get {
                return ResourceManager.GetString("EmpresaGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresas.
        /// </summary>
        public static string Empresas {
            get {
                return ResourceManager.GetString("Empresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar Contraseña.
        /// </summary>
        public static string EnvioPass {
            get {
                return ResourceManager.GetString("EnvioPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE_ERROR_ENVIO_CONTRASEÑA.
        /// </summary>
        public static string EnvioPassErrorCorreo {
            get {
                return ResourceManager.GetString("EnvioPassErrorCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE_ERROR_USUARIO_NO_REGISTRADO.
        /// </summary>
        public static string EnvioPassOlvidadoError {
            get {
                return ResourceManager.GetString("EnvioPassOlvidadoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE_EXITO_ENVIO_CONTRASEÑA.
        /// </summary>
        public static string EnvioPassOlvidadoExito {
            get {
                return ResourceManager.GetString("EnvioPassOlvidadoExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al Borrar el Grupo.
        /// </summary>
        public static string ErroBorrarGrupo {
            get {
                return ResourceManager.GetString("ErroBorrarGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al asignar las emisoras..
        /// </summary>
        public static string ErrorEmisorasAsignadas {
            get {
                return ResourceManager.GetString("ErrorEmisorasAsignadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al asignar las facultades..
        /// </summary>
        public static string ErrorFacultadesAsignados {
            get {
                return ResourceManager.GetString("ErrorFacultadesAsignados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al Generara la Contraseña.
        /// </summary>
        public static string ErrorGenerarContrasena {
            get {
                return ResourceManager.GetString("ErrorGenerarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al Guardar el Grupo.
        /// </summary>
        public static string ErrorGrupoGuardado {
            get {
                return ResourceManager.GetString("ErrorGrupoGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al asignar los roles..
        /// </summary>
        public static string ErrorRolesAsignados {
            get {
                return ResourceManager.GetString("ErrorRolesAsignados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al Asignar Roles al Grupo.
        /// </summary>
        public static string ErrorRolesGruposAsignados {
            get {
                return ResourceManager.GetString("ErrorRolesGruposAsignados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE_ERROR_BORRAR_USUARIO.
        /// </summary>
        public static string ErrorUsuarioBorrardo {
            get {
                return ResourceManager.GetString("ErrorUsuarioBorrardo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE_ERROR_USUARIO_GUARDADO.
        /// </summary>
        public static string ErrorUsuarioGuardado {
            get {
                return ResourceManager.GetString("ErrorUsuarioGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE_ERROR_USUARIO_OPERACION.
        /// </summary>
        public static string ErrorUsuarioOperacion {
            get {
                return ResourceManager.GetString("ErrorUsuarioOperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al Asignar Usuarios al Grupo.
        /// </summary>
        public static string ErrorUsuariosGruposAsignados {
            get {
                return ResourceManager.GetString("ErrorUsuariosGruposAsignados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar a Excel.
        /// </summary>
        public static string Exportar {
            get {
                return ResourceManager.GetString("Exportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facultad.
        /// </summary>
        public static string Facultad {
            get {
                return ResourceManager.GetString("Facultad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facultades.
        /// </summary>
        public static string Facultades {
            get {
                return ResourceManager.GetString("Facultades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facultades Asignadas.
        /// </summary>
        public static string FacultadesAsignadas {
            get {
                return ResourceManager.GetString("FacultadesAsignadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facultades Asignados Correctamente..
        /// </summary>
        public static string FacultadesAsignadosCorrectamente {
            get {
                return ResourceManager.GetString("FacultadesAsignadosCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facultades No Asignadas.
        /// </summary>
        public static string FacultadesNoAsignadas {
            get {
                return ResourceManager.GetString("FacultadesNoAsignadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar Nueva Contraseña.
        /// </summary>
        public static string GenerarNuevaContrasena {
            get {
                return ResourceManager.GetString("GenerarNuevaContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Guardado Correctamente.
        /// </summary>
        public static string GrupoGuardado {
            get {
                return ResourceManager.GetString("GrupoGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisiones registradas en el catálogo.
        /// </summary>
        public static string GruposRegistrados {
            get {
                return ResourceManager.GetString("GruposRegistrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar.
        /// </summary>
        public static string Importar {
            get {
                return ResourceManager.GetString("Importar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        public static string Inactivo {
            get {
                return ResourceManager.GetString("Inactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacion Requerida.
        /// </summary>
        public static string InformacionRequerida {
            get {
                return ResourceManager.GetString("InformacionRequerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        public static string IniciarSesion {
            get {
                return ResourceManager.GetString("IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir.
        /// </summary>
        public static string Ir {
            get {
                return ResourceManager.GetString("Ir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción.
        /// </summary>
        public static string LabelAccionBitacora {
            get {
                return ResourceManager.GetString("LabelAccionBitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido Materno.
        /// </summary>
        public static string LabelApellidoMaterno {
            get {
                return ResourceManager.GetString("LabelApellidoMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido Paterno.
        /// </summary>
        public static string LabelApellidoPaterno {
            get {
                return ResourceManager.GetString("LabelApellidoPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electrónico.
        /// </summary>
        public static string LabelCorreoElectronico {
            get {
                return ResourceManager.GetString("LabelCorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emisora.
        /// </summary>
        public static string LabelEmisoraBitacora {
            get {
                return ResourceManager.GetString("LabelEmisoraBitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string LabelFechaBitacora {
            get {
                return ResourceManager.GetString("LabelFechaBitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        public static string LabelGrupo {
            get {
                return ResourceManager.GetString("LabelGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puesto.
        /// </summary>
        public static string LabelPuesto {
            get {
                return ResourceManager.GetString("LabelPuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro.
        /// </summary>
        public static string LabelRegistroBitacora {
            get {
                return ResourceManager.GetString("LabelRegistroBitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string LabelUsuarioBitacora {
            get {
                return ResourceManager.GetString("LabelUsuarioBitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo.
        /// </summary>
        public static string LabeModuloBitacora {
            get {
                return ResourceManager.GetString("LabeModuloBitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Grupos.
        /// </summary>
        public static string ListadoDeGrupos {
            get {
                return ResourceManager.GetString("ListadoDeGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Empresas.
        /// </summary>
        public static string ListadoEmpresas {
            get {
                return ResourceManager.GetString("ListadoEmpresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Roles.
        /// </summary>
        public static string ListadoRoles {
            get {
                return ResourceManager.GetString("ListadoRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Usuarios.
        /// </summary>
        public static string ListadoUsuarios {
            get {
                return ResourceManager.GetString("ListadoUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrando.
        /// </summary>
        public static string Mostrando {
            get {
                return ResourceManager.GetString("Mostrando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre corto.
        /// </summary>
        public static string NombreCorto {
            get {
                return ResourceManager.GetString("NombreCorto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre corto de la empresa es vacio.
        /// </summary>
        public static string NombreCortoEmpresaVacio {
            get {
                return ResourceManager.GetString("NombreCortoEmpresaVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string NombreGrupo {
            get {
                return ResourceManager.GetString("NombreGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del grupo es requerido.
        /// </summary>
        public static string NombreGrupoVacio {
            get {
                return ResourceManager.GetString("NombreGrupoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Rol.
        /// </summary>
        public static string NombreRolEtiqueta {
            get {
                return ResourceManager.GetString("NombreRolEtiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del rol es requerido.
        /// </summary>
        public static string NombreRolVacia {
            get {
                return ResourceManager.GetString("NombreRolVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre(s).
        /// </summary>
        public static string Nombres {
            get {
                return ResourceManager.GetString("Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del usuario es requerido.
        /// </summary>
        public static string NombreVacio {
            get {
                return ResourceManager.GetString("NombreVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidó su Password?.
        /// </summary>
        public static string OlvidoContraseña {
            get {
                return ResourceManager.GetString("OlvidoContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas.
        /// </summary>
        public static string OpcionTodas {
            get {
                return ResourceManager.GetString("OpcionTodas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagina.
        /// </summary>
        public static string Pagina {
            get {
                return ResourceManager.GetString("Pagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Para {
            get {
                return ResourceManager.GetString("Para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE_ERROR_AUTENTICAR_SIN_CONTRASENA.
        /// </summary>
        public static string PassReq {
            get {
                return ResourceManager.GetString("PassReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña Anterior.
        /// </summary>
        public static string PasswordAnterior {
            get {
                return ResourceManager.GetString("PasswordAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Contraseña.
        /// </summary>
        public static string PasswordConfirmar {
            get {
                return ResourceManager.GetString("PasswordConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Constraseña.
        /// </summary>
        public static string PasswordNuevo {
            get {
                return ResourceManager.GetString("PasswordNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Está seguro que desea eliminar este grupo del usuario?.
        /// </summary>
        public static string PreguntaEliminar {
            get {
                return ResourceManager.GetString("PreguntaEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Está seguro que desea eliminar esta empresa?.
        /// </summary>
        public static string PreguntaEliminarEmpresa {
            get {
                return ResourceManager.GetString("PreguntaEliminarEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Está seguro que desea eliminar este rol?.
        /// </summary>
        public static string PreguntaEliminarRol {
            get {
                return ResourceManager.GetString("PreguntaEliminarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Está seguro que desea eliminar este Usuario?.
        /// </summary>
        public static string PreguntaEliminarUsuario {
            get {
                return ResourceManager.GetString("PreguntaEliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puesto.
        /// </summary>
        public static string Puesto {
            get {
                return ResourceManager.GetString("Puesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razón social .
        /// </summary>
        public static string RazonSocial {
            get {
                return ResourceManager.GetString("RazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La razon social es requerida.
        /// </summary>
        public static string RazonSocialVacio {
            get {
                return ResourceManager.GetString("RazonSocialVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar Nueva Empresa.
        /// </summary>
        public static string RegistrarNuevaEmpresa {
            get {
                return ResourceManager.GetString("RegistrarNuevaEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar Grupo.
        /// </summary>
        public static string RegistrarNuevaGrupo {
            get {
                return ResourceManager.GetString("RegistrarNuevaGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar nuevo Grupo.
        /// </summary>
        public static string RegistrarNuevoGrupo {
            get {
                return ResourceManager.GetString("RegistrarNuevoGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar Nuevo Rol.
        /// </summary>
        public static string RegistrarNuevRol {
            get {
                return ResourceManager.GetString("RegistrarNuevRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar Usuario.
        /// </summary>
        public static string RegistrarUsuario {
            get {
                return ResourceManager.GetString("RegistrarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar.
        /// </summary>
        public static string Regresar {
            get {
                return ResourceManager.GetString("Regresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC.
        /// </summary>
        public static string RFC {
            get {
                return ResourceManager.GetString("RFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El RFC no cuenta con un formato válido.
        /// </summary>
        public static string RfcSinFormato {
            get {
                return ResourceManager.GetString("RfcSinFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC requerido.
        /// </summary>
        public static string RFCVacio {
            get {
                return ResourceManager.GetString("RFCVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol Borrado Correctamente.
        /// </summary>
        public static string RolBorrado {
            get {
                return ResourceManager.GetString("RolBorrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al Borrar el Rol.
        /// </summary>
        public static string RolErrorBorrar {
            get {
                return ResourceManager.GetString("RolErrorBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al Guardar el Rol.
        /// </summary>
        public static string RolErrorGuardar {
            get {
                return ResourceManager.GetString("RolErrorGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Asignados Correctamente..
        /// </summary>
        public static string RolesAsignadosCorrectamente {
            get {
                return ResourceManager.GetString("RolesAsignadosCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Actualmente Asignados..
        /// </summary>
        public static string RolesAsingados {
            get {
                return ResourceManager.GetString("RolesAsingados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Disponibles..
        /// </summary>
        public static string RolesDisponibles {
            get {
                return ResourceManager.GetString("RolesDisponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string RolesGrupo {
            get {
                return ResourceManager.GetString("RolesGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Asignados al Grupo Correctamente.
        /// </summary>
        public static string RolesGruposAsignados {
            get {
                return ResourceManager.GetString("RolesGruposAsignados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles No Seleccionados..
        /// </summary>
        public static string RolesNoSeleccionados {
            get {
                return ResourceManager.GetString("RolesNoSeleccionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Seleccionados..
        /// </summary>
        public static string RolesSeleccionados {
            get {
                return ResourceManager.GetString("RolesSeleccionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol Guardado Correctamente.
        /// </summary>
        public static string RolGuardado {
            get {
                return ResourceManager.GetString("RolGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string RolTabla {
            get {
                return ResourceManager.GetString("RolTabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una Emisora....
        /// </summary>
        public static string SeleccionarEmisora {
            get {
                return ResourceManager.GetString("SeleccionarEmisora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una Emisora Válida.
        /// </summary>
        public static string SeleccioneEmisoraValida {
            get {
                return ResourceManager.GetString("SeleccioneEmisoraValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es requerido tener al menos una emisora asignada, antes de asignar roles al usuario..
        /// </summary>
        public static string SeRequireTenerUnaEmpresaAsignada {
            get {
                return ResourceManager.GetString("SeRequireTenerUnaEmpresaAsignada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han encontrado resultados.
        /// </summary>
        public static string SinResultados {
            get {
                return ResourceManager.GetString("SinResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Rol.
        /// </summary>
        public static string SubTituloEditarRol {
            get {
                return ResourceManager.GetString("SubTituloEditarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar Rol.
        /// </summary>
        public static string SubTituloRegistrarRol {
            get {
                return ResourceManager.GetString("SubTituloRegistrarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitácora de Auditoria.
        /// </summary>
        public static string TituloBitacoraAuditoria {
            get {
                return ResourceManager.GetString("TituloBitacoraAuditoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de Empresas.
        /// </summary>
        public static string TituloCatalogoEmpresa {
            get {
                return ResourceManager.GetString("TituloCatalogoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de Roles.
        /// </summary>
        public static string TituloCatalogoRol {
            get {
                return ResourceManager.GetString("TituloCatalogoRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historial de Actividad.
        /// </summary>
        public static string TituloConsultaBitacora {
            get {
                return ResourceManager.GetString("TituloConsultaBitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos Instancia XBRL.
        /// </summary>
        public static string TituloDocumentosInstancia {
            get {
                return ResourceManager.GetString("TituloDocumentosInstancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string TituloEditar {
            get {
                return ResourceManager.GetString("TituloEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Empresa.
        /// </summary>
        public static string TituloEditarEmpresa {
            get {
                return ResourceManager.GetString("TituloEditarEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string TituloEliminar {
            get {
                return ResourceManager.GetString("TituloEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emisora.
        /// </summary>
        public static string TituloEmisora {
            get {
                return ResourceManager.GetString("TituloEmisora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string TituloEstadoDoc {
            get {
                return ResourceManager.GetString("TituloEstadoDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Creación.
        /// </summary>
        public static string TituloFechaCreacion {
            get {
                return ResourceManager.GetString("TituloFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Última Modificación.
        /// </summary>
        public static string TituloFechaUltimaMod {
            get {
                return ResourceManager.GetString("TituloFechaUltimaMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Documentos de Instancia.
        /// </summary>
        public static string TituloListadoDocumentosInstancia {
            get {
                return ResourceManager.GetString("TituloListadoDocumentosInstancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Documento.
        /// </summary>
        public static string TituloNombreDoc {
            get {
                return ResourceManager.GetString("TituloNombreDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar Nueva Empresa.
        /// </summary>
        public static string TituloRegistrarEmpresa {
            get {
                return ResourceManager.GetString("TituloRegistrarEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogo de Roles.
        /// </summary>
        public static string TituloRegistrarRol {
            get {
                return ResourceManager.GetString("TituloRegistrarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos Compartidos.
        /// </summary>
        public static string TituloSeccionDocumentosCompartidos {
            get {
                return ResourceManager.GetString("TituloSeccionDocumentosCompartidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Documentos.
        /// </summary>
        public static string TituloSeccionMisDocumentos {
            get {
                return ResourceManager.GetString("TituloSeccionMisDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxonomía.
        /// </summary>
        public static string TituloTaxonomia {
            get {
                return ResourceManager.GetString("TituloTaxonomia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Última Modificación.
        /// </summary>
        public static string TituloUsuarioUltimaMod {
            get {
                return ResourceManager.GetString("TituloUsuarioUltimaMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimo Acceso.
        /// </summary>
        public static string UltimoAcceso {
            get {
                return ResourceManager.GetString("UltimoAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE_EXITO_USUARIO_ACTIVADO.
        /// </summary>
        public static string UsuarioActivo {
            get {
                return ResourceManager.GetString("UsuarioActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Bloqueado.
        /// </summary>
        public static string UsuarioBloquead {
            get {
                return ResourceManager.GetString("UsuarioBloquead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE_EXITO_USUARIO_BLOQUEADO.
        /// </summary>
        public static string UsuarioBloqueado {
            get {
                return ResourceManager.GetString("UsuarioBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Borrado Correctamente.
        /// </summary>
        public static string UsuarioBorrado {
            get {
                return ResourceManager.GetString("UsuarioBorrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un usuario registrado con el correo proporcionado.
        /// </summary>
        public static string UsuarioConCorreoExistente {
            get {
                return ResourceManager.GetString("UsuarioConCorreoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE_EXITO_USUARIO_DESACTIVADO.
        /// </summary>
        public static string UsuarioDesactivado {
            get {
                return ResourceManager.GetString("UsuarioDesactivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE_EXITO_USUARIO_DESBLOQUEADO.
        /// </summary>
        public static string UsuarioDesbloqueado {
            get {
                return ResourceManager.GetString("UsuarioDesbloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsuarioDesctivado.
        /// </summary>
        public static string UsuarioDescativado {
            get {
                return ResourceManager.GetString("UsuarioDescativado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE_EXITO_USUARIO_GUARDADO.
        /// </summary>
        public static string UsuarioGuardado {
            get {
                return ResourceManager.GetString("UsuarioGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE_WARNING_USUARIO_NO_ENCONTRADO.
        /// </summary>
        public static string UsuarioNoEncontrado {
            get {
                return ResourceManager.GetString("UsuarioNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string Usuarios {
            get {
                return ResourceManager.GetString("Usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios Asignados..
        /// </summary>
        public static string UsuariosAsigados {
            get {
                return ResourceManager.GetString("UsuariosAsigados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string UsuariosGrupo {
            get {
                return ResourceManager.GetString("UsuariosGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios Asignados al Grupo Correctamente.
        /// </summary>
        public static string UsuariosGruposAsignados {
            get {
                return ResourceManager.GetString("UsuariosGruposAsignados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios Por Asignar..
        /// </summary>
        public static string UsuariosPorAsigar {
            get {
                return ResourceManager.GetString("UsuariosPorAsigar", resourceCulture);
            }
        }
    }
}
