//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MensajesRepositorios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajesRepositorios() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbaxXBRLCore.lang.MensajesRepositorios", typeof(MensajesRepositorios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accion Auditable Actualizada Correctamente.
        /// </summary>
        internal static string AccionAuditableActualizar {
            get {
                return ResourceManager.GetString("AccionAuditableActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accion Auditable Correctamente.
        /// </summary>
        internal static string AccionAuditableGuardar {
            get {
                return ResourceManager.GetString("AccionAuditableGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria Facultad  Actualizada Correctamente.
        /// </summary>
        internal static string CategoriaFacultadActualizar {
            get {
                return ResourceManager.GetString("CategoriaFacultadActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria Facultad Correctamente.
        /// </summary>
        internal static string CategoriaFacultadGuardar {
            get {
                return ResourceManager.GetString("CategoriaFacultadGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa Actualizada Correctamente.
        /// </summary>
        internal static string EmpresaActualizar {
            get {
                return ResourceManager.GetString("EmpresaActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa Registrada Correctamente.
        /// </summary>
        internal static string EmpresaGuardar {
            get {
                return ResourceManager.GetString("EmpresaGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facultad  Actualizada Correctamente.
        /// </summary>
        internal static string FacultadActualizar {
            get {
                return ResourceManager.GetString("FacultadActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facultad Correctamente.
        /// </summary>
        internal static string FacultadGuardar {
            get {
                return ResourceManager.GetString("FacultadGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Usuarios  Actualizada Correctamente.
        /// </summary>
        internal static string GrupoUsuarioActualizar {
            get {
                return ResourceManager.GetString("GrupoUsuarioActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Usuarios Correctamente&quot;.
        /// </summary>
        internal static string GrupoUsuarioGuardar {
            get {
                return ResourceManager.GetString("GrupoUsuarioGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Usuarios Rol  Actualizado Correctamente.
        /// </summary>
        internal static string GrupoUsuarioRolActualizar {
            get {
                return ResourceManager.GetString("GrupoUsuarioRolActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Usuarios Rol Guardado Correctamente.
        /// </summary>
        internal static string GrupoUsuarioRolGuardar {
            get {
                return ResourceManager.GetString("GrupoUsuarioRolGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulo Actualizado Correctamente.
        /// </summary>
        internal static string ModuloActualizar {
            get {
                return ResourceManager.GetString("ModuloActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulo Guardado Correctamente.
        /// </summary>
        internal static string ModuloGuardar {
            get {
                return ResourceManager.GetString("ModuloGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Auditoria Actualizado Correctamente.
        /// </summary>
        internal static string RegistroAuditoriaActualizar {
            get {
                return ResourceManager.GetString("RegistroAuditoriaActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Auditoria Guardado Correctamente.
        /// </summary>
        internal static string RegistroAuditoriaGuardar {
            get {
                return ResourceManager.GetString("RegistroAuditoriaGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol Actualizado Correctamente.
        /// </summary>
        internal static string RolActualizar {
            get {
                return ResourceManager.GetString("RolActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolFacultad Guardado Correctamente.
        /// </summary>
        internal static string RolFacultadGuardar {
            get {
                return ResourceManager.GetString("RolFacultadGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolFacultad Actualizado Correctamente.
        /// </summary>
        internal static string RolFacultarActualizar {
            get {
                return ResourceManager.GetString("RolFacultarActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol Guardado Correctamente.
        /// </summary>
        internal static string RolGuardar {
            get {
                return ResourceManager.GetString("RolGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE_EXITO_USUARIO_ACTUALIZADO.
        /// </summary>
        internal static string UsuarioActualizar {
            get {
                return ResourceManager.GetString("UsuarioActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Empresa Actualizada Correctamente.
        /// </summary>
        internal static string UsuarioEmpresaActualizar {
            get {
                return ResourceManager.GetString("UsuarioEmpresaActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Empresa Registrada Correctamente.
        /// </summary>
        internal static string UsuarioEmpresaGuardar {
            get {
                return ResourceManager.GetString("UsuarioEmpresaGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Grupo Actualizado Correctamente.
        /// </summary>
        internal static string UsuarioGrupoActualizar {
            get {
                return ResourceManager.GetString("UsuarioGrupoActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Grupo Guardado Correctamente.
        /// </summary>
        internal static string UsuarioGrupoGuardar {
            get {
                return ResourceManager.GetString("UsuarioGrupoGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE_EXITO_USUARIO_REGISTRADO.
        /// </summary>
        internal static string UsuarioGuardar {
            get {
                return ResourceManager.GetString("UsuarioGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Rol Actualizado Correctamente.
        /// </summary>
        internal static string UsuarioRolActualizar {
            get {
                return ResourceManager.GetString("UsuarioRolActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Rol Guardado Correctamente.
        /// </summary>
        internal static string UsuarioRolGuardar {
            get {
                return ResourceManager.GetString("UsuarioRolGuardar", resourceCulture);
            }
        }
    }
}
