//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MensajesServicios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajesServicios() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbaxXBRLCore.lang.MensajesServicios", typeof(MensajesServicios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario activo al usuario {0}.
        /// </summary>
        internal static string ActivacionUsuario {
            get {
                return ResourceManager.GetString("ActivacionUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario actualizó la información de la consulta al repositorio &quot;{0}&quot;({1})..
        /// </summary>
        internal static string ActualizaConsultaRepositorio {
            get {
                return ResourceManager.GetString("ActualizaConsultaRepositorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario actualizo el destinatario &quot;{0}&quot; de la lista de notificación &quot;{1}&quot;.
        /// </summary>
        internal static string ActualizarDestinatarioNotificacion {
            get {
                return ResourceManager.GetString("ActualizarDestinatarioNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario actualizó los datos de la emisora {0}.
        /// </summary>
        internal static string ActualizarEmpresa {
            get {
                return ResourceManager.GetString("ActualizarEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario actualizó los datos generales del grupo de usuarios {0}.
        /// </summary>
        internal static string ActualizarGrupo {
            get {
                return ResourceManager.GetString("ActualizarGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario actualizó la información del grupo de empresas &quot;{0}&quot; ({1})..
        /// </summary>
        internal static string ActualizarGrupoEmpresa {
            get {
                return ResourceManager.GetString("ActualizarGrupoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario actualizo la lista de notificación &quot;{0}&quot;.
        /// </summary>
        internal static string ActualizarListaNotificacion {
            get {
                return ResourceManager.GetString("ActualizarListaNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario actualizó el valor del parametro de sistema &quot;{0}&quot; ({1})..
        /// </summary>
        internal static string ActualizarParametroSistema {
            get {
                return ResourceManager.GetString("ActualizarParametroSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario actualizó el listado de empresas asignadas al grupo &quot;{0}&quot;..
        /// </summary>
        internal static string ActualizarRelacioesGrupoEmpresaAempresa {
            get {
                return ResourceManager.GetString("ActualizarRelacioesGrupoEmpresaAempresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario actualizó el listado de grupos de empresa a los que pertenece la empresa &quot;{0}&quot;..
        /// </summary>
        internal static string ActualizarRelacionesEmpresaAgruposEmprea {
            get {
                return ResourceManager.GetString("ActualizarRelacionesEmpresaAgruposEmprea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario actualizó los datos rol con el nombre {0}.
        /// </summary>
        internal static string ActualizarRol {
            get {
                return ResourceManager.GetString("ActualizarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario actualizó la taxonomía xbrl &quot;{0}&quot;.
        /// </summary>
        internal static string ActualizarTaxonomiaXbrl {
            get {
                return ResourceManager.GetString("ActualizarTaxonomiaXbrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario actualizo el tipo de empresa &quot;{0}&quot;.
        /// </summary>
        internal static string ActualizarTipoEmpresa {
            get {
                return ResourceManager.GetString("ActualizarTipoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario actualizó los datos generales del usuario {0}.
        /// </summary>
        internal static string Actualizarusuario {
            get {
                return ResourceManager.GetString("Actualizarusuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuariio {0} actualizó la relacion Usuario - Empresa {1}.
        /// </summary>
        internal static string ActualizarUsuarioEmpresa {
            get {
                return ResourceManager.GetString("ActualizarUsuarioEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario asignó roles al grupo {0}.
        /// </summary>
        internal static string AsignacionRolesAGrupos {
            get {
                return ResourceManager.GetString("AsignacionRolesAGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se han asignado facultades al rol {0}.
        /// </summary>
        internal static string AsignarFacultadesARoles {
            get {
                return ResourceManager.GetString("AsignarFacultadesARoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario actualizó el listado de fideicomitentes asignados al fiduciario {0}.
        /// </summary>
        internal static string AsignarFideicomitentes {
            get {
                return ResourceManager.GetString("AsignarFideicomitentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario actualizó el listado de taxonomías xbrl asignadas al tipo de empresa {0}.
        /// </summary>
        internal static string AsignarTaxonomiasXbrl {
            get {
                return ResourceManager.GetString("AsignarTaxonomiasXbrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario actualizó el listado de tipos de empresa asignados a la empresa &quot;{0}&quot;.
        /// </summary>
        internal static string AsignarTiposEmpresa {
            get {
                return ResourceManager.GetString("AsignarTiposEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario realizo asignacion de usuarios al grupo {0}.
        /// </summary>
        internal static string AsignarUsuariosGrupo {
            get {
                return ResourceManager.GetString("AsignarUsuariosGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ha bloqueado para edición el documento instancia {0}.
        /// </summary>
        internal static string BloquearLiberarDocumentoInstancia {
            get {
                return ResourceManager.GetString("BloquearLiberarDocumentoInstancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario bloqueo al usuario {0}.
        /// </summary>
        internal static string BloqueoUsuario {
            get {
                return ResourceManager.GetString("BloqueoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario eliminó la consulta al repositorio &quot;{0}&quot; ({1})..
        /// </summary>
        internal static string BorrarConsultaRepositorio {
            get {
                return ResourceManager.GetString("BorrarConsultaRepositorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario borro el destinatario de notificación &quot;{0}&quot; de la lista de notificación &quot;{1}&quot;.
        /// </summary>
        internal static string BorrarDestinatarioNotificacion {
            get {
                return ResourceManager.GetString("BorrarDestinatarioNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario eliminó a la empresa {0}.
        /// </summary>
        internal static string BorrarEmpresa {
            get {
                return ResourceManager.GetString("BorrarEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario {0} borro el grupo  {1}.
        /// </summary>
        internal static string BorrarGrupo {
            get {
                return ResourceManager.GetString("BorrarGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario elimino el grupo de empresas &quot;{0}&quot; ({1}) con todas sus relaciones..
        /// </summary>
        internal static string BorrarGrupoEmpresa {
            get {
                return ResourceManager.GetString("BorrarGrupoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario borro el grupo de usuarios {0}.
        /// </summary>
        internal static string BorrarGrupoUsuario {
            get {
                return ResourceManager.GetString("BorrarGrupoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario {0} borro la asignación de grupo-rol con id {1}.
        /// </summary>
        internal static string BorrarGrupoUsuariosRol {
            get {
                return ResourceManager.GetString("BorrarGrupoUsuariosRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario borro la lista de notificación &quot;{0}&quot;.
        /// </summary>
        internal static string BorrarListaNotificacion {
            get {
                return ResourceManager.GetString("BorrarListaNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario borro el rol con el nombre {0}.
        /// </summary>
        internal static string BorrarRol {
            get {
                return ResourceManager.GetString("BorrarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario borró la taxonomía xbrl &quot;{0}&quot;.
        /// </summary>
        internal static string BorrarTaxonomiaXbrl {
            get {
                return ResourceManager.GetString("BorrarTaxonomiaXbrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario borro el tipo de empresa &quot;{0}&quot;.
        /// </summary>
        internal static string BorrarTipoEmpresa {
            get {
                return ResourceManager.GetString("BorrarTipoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario eliminó al usuario con el correo electrónico {0}.
        /// </summary>
        internal static string BorrarUsuario {
            get {
                return ResourceManager.GetString("BorrarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario {0} borro la realcion Usuario - Empresa {1}.
        /// </summary>
        internal static string BorrarUsuarioEmpresa {
            get {
                return ResourceManager.GetString("BorrarUsuarioEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario {0} desasignó al usuario {1} .
        /// </summary>
        internal static string BorrarUsuarioGrupo {
            get {
                return ResourceManager.GetString("BorrarUsuarioGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario desasignó roles al usuario {0}.
        /// </summary>
        internal static string BorrarUsuarioRol {
            get {
                return ResourceManager.GetString("BorrarUsuarioRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE_WARNING_CONTRASENA_INCORRECTA.
        /// </summary>
        internal static string ContrasenaIncorrecta {
            get {
                return ResourceManager.GetString("ContrasenaIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha modificado la contraseña.
        /// </summary>
        internal static string ContrasenaModificada {
            get {
                return ResourceManager.GetString("ContrasenaModificada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ha modificado su password exitósamente.
        /// </summary>
        internal static string ContraseñaModificada {
            get {
                return ResourceManager.GetString("ContraseñaModificada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se mandó depurar la bitácora de actividades a partir de la fecha {0}..
        /// </summary>
        internal static string DepurarBitacora {
            get {
                return ResourceManager.GetString("DepurarBitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario desactivo al usuario {0}.
        /// </summary>
        internal static string DesactivacionUsuario {
            get {
                return ResourceManager.GetString("DesactivacionUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario desbloqueo al usuario {0}.
        /// </summary>
        internal static string DesbloqueoUsuario {
            get {
                return ResourceManager.GetString("DesbloqueoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se solicito un correo por olvido de la constraseña.
        /// </summary>
        internal static string EnvioCorreoOlvidoContraseña {
            get {
                return ResourceManager.GetString("EnvioCorreoOlvidoContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario exportó a Excel el catálogo de Consultas al Repositorio..
        /// </summary>
        internal static string ExportarExcelConsultasRepositorio {
            get {
                return ResourceManager.GetString("ExportarExcelConsultasRepositorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario exportó a excel los destinatarios de la lista de notificación &quot;{0}&quot;..
        /// </summary>
        internal static string ExportarExcelDestinatariosNotificacion {
            get {
                return ResourceManager.GetString("ExportarExcelDestinatariosNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario exportó a excel el catálogo de grupos de empresas..
        /// </summary>
        internal static string ExportarExcelGrupoEmpresas {
            get {
                return ResourceManager.GetString("ExportarExcelGrupoEmpresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario exportó a excel el catálogo de listas de notificación..
        /// </summary>
        internal static string ExportarExcelListasNotificacion {
            get {
                return ResourceManager.GetString("ExportarExcelListasNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario exportó a excel el catálogo de parametros del sistema..
        /// </summary>
        internal static string ExportarExcelParametrosSistema {
            get {
                return ResourceManager.GetString("ExportarExcelParametrosSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario exportó a excel el catálogo de tipos de empresas..
        /// </summary>
        internal static string ExportarExcelTiposEmpresa {
            get {
                return ResourceManager.GetString("ExportarExcelTiposEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ha exportado en formato Excel el documento instancia {0}.
        /// </summary>
        internal static string ExportarFormatoAExcel {
            get {
                return ResourceManager.GetString("ExportarFormatoAExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La autentificación del usuario no fue exitosa.
        /// </summary>
        internal static string FalloUsuarioAutentificado {
            get {
                return ResourceManager.GetString("FalloUsuarioAutentificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ha exportado en formato XBRL el documento instancia {0}.
        /// </summary>
        internal static string GenerarXbrl {
            get {
                return ResourceManager.GetString("GenerarXbrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ha importado información a partir de un documento de Excel al documento instancia {0}.
        /// </summary>
        internal static string ImportarDatosDeExcel {
            get {
                return ResourceManager.GetString("ImportarDatosDeExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario a registrado una nuevo consulta del repositorio llamada &quot;{0}&quot;({1})..
        /// </summary>
        internal static string InsertarConsultaRepositorio {
            get {
                return ResourceManager.GetString("InsertarConsultaRepositorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario inserto el nuevo destinatario &quot;{0}&quot; en la lista de notificación &quot;{1}&quot;.
        /// </summary>
        internal static string InsertarDestinatarioNotificacion {
            get {
                return ResourceManager.GetString("InsertarDestinatarioNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario registro una nueva emisora con el nombre {0}.
        /// </summary>
        internal static string InsertarEmpresa {
            get {
                return ResourceManager.GetString("InsertarEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario registro un nuevo grupo de usuarios con el nombre {0}.
        /// </summary>
        internal static string InsertarGrupo {
            get {
                return ResourceManager.GetString("InsertarGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario inserto el nuevo grupo de empresas &quot;{0}&quot; ({1})..
        /// </summary>
        internal static string InsertarGrupoEmpresa {
            get {
                return ResourceManager.GetString("InsertarGrupoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario {0} asignó el rol {1} al grupo {2}.
        /// </summary>
        internal static string InsertarGrupoUsuariosRol {
            get {
                return ResourceManager.GetString("InsertarGrupoUsuariosRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario inserto la nueva lista de notificación &quot;{0}&quot;.
        /// </summary>
        internal static string InsertarListaNotificacion {
            get {
                return ResourceManager.GetString("InsertarListaNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario registro un nuevo rol con el nombre {0}.
        /// </summary>
        internal static string InsertarRol {
            get {
                return ResourceManager.GetString("InsertarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario insertó la nueva taxonomía xbrl &quot;{0}&quot;.
        /// </summary>
        internal static string InsertarTaxonomiaXbrl {
            get {
                return ResourceManager.GetString("InsertarTaxonomiaXbrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario inserto el nuevo tipo de empresa &quot;{0}&quot;.
        /// </summary>
        internal static string InsertarTipoEmpresa {
            get {
                return ResourceManager.GetString("InsertarTipoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario registro un nuevo usuario con el correo {0}.
        /// </summary>
        internal static string InsertarUsuario {
            get {
                return ResourceManager.GetString("InsertarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario asignó una empresa al usuario {0}.
        /// </summary>
        internal static string InsertarUsuarioEmpresa {
            get {
                return ResourceManager.GetString("InsertarUsuarioEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario {0} asignó al usuario {1} al grupo {2}.
        /// </summary>
        internal static string InsertarUsuarioGrupo {
            get {
                return ResourceManager.GetString("InsertarUsuarioGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario asignó roles al usuario {0}.
        /// </summary>
        internal static string InsertarUsuarioRol {
            get {
                return ResourceManager.GetString("InsertarUsuarioRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE_WARNING_INTENTOS_EXCEDIDOS.
        /// </summary>
        internal static string IntentosExcedidos {
            get {
                return ResourceManager.GetString("IntentosExcedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ha desbloqueado el documento instancia {0}.
        /// </summary>
        internal static string LiberarDocumentoInstancia {
            get {
                return ResourceManager.GetString("LiberarDocumentoInstancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario consultó del documento instancia {0}.
        /// </summary>
        internal static string ObtenerFormatoCaptura {
            get {
                return ResourceManager.GetString("ObtenerFormatoCaptura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ha consultado la versión {0} del documento instancia {1}.
        /// </summary>
        internal static string ObtenerFormatoCapturaHistorico {
            get {
                return ResourceManager.GetString("ObtenerFormatoCapturaHistorico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se registro un acceso a la aplicación.
        /// </summary>
        internal static string RegistroAcceso {
            get {
                return ResourceManager.GetString("RegistroAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron datos del usuario.
        /// </summary>
        internal static string SinDatosUsuario {
            get {
                return ResourceManager.GetString("SinDatosUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario se autentificó en la aplicación.
        /// </summary>
        internal static string UsuarioAutenficado {
            get {
                return ResourceManager.GetString("UsuarioAutenficado", resourceCulture);
            }
        }
    }
}
