/****** Object:  Index [IX_IdConcepto]    Script Date: 23/02/2015 10:18:43 ******/
CREATE NONCLUSTERED INDEX [IX_IdConcepto] ON [dbo].[Hecho]
(
	[IdConcepto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Index [IX_IdContexto]    Script Date: 23/02/2015 10:18:58 ******/
CREATE NONCLUSTERED INDEX [IX_IdContexto] ON [dbo].[Hecho]
(
	[IdContexto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Index [IX_IdDocumentoInstancia]    Script Date: 23/02/2015 10:19:12 ******/
CREATE NONCLUSTERED INDEX [IX_IdDocumentoInstancia] ON [dbo].[Hecho]
(
	[IdDocumentoInstancia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Index [IX_IdUnidad]    Script Date: 23/02/2015 10:19:32 ******/
CREATE NONCLUSTERED INDEX [IX_IdUnidad] ON [dbo].[Hecho]
(
	[IdUnidad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO