IF NOT EXISTS( SELECT * FROM [dbo].[PeriodicidadReporte] WHERE [IdPeriodicidadReporte] = 1)
BEGIN
INSERT [dbo].[PeriodicidadReporte] ([IdPeriodicidadReporte], [Nombre], [Descripcion]) VALUES (1, N'Trimestral', N'Información reportada cada tres meses')
END
GO
IF NOT EXISTS( SELECT * FROM [dbo].[PeriodicidadReporte] WHERE [IdPeriodicidadReporte] = 2)
BEGIN
INSERT [dbo].[PeriodicidadReporte] ([IdPeriodicidadReporte], [Nombre], [Descripcion]) VALUES (2, N'Mensual', N'Información reportada cada mes')
END
GO
IF NOT EXISTS( SELECT * FROM [dbo].[PeriodicidadReporte] WHERE [IdPeriodicidadReporte] = 3)
BEGIN
INSERT [dbo].[PeriodicidadReporte] ([IdPeriodicidadReporte], [Nombre], [Descripcion]) VALUES (3, N'Anual', N'Información reportada cada año')
END
GO
IF NOT EXISTS( SELECT * FROM [dbo].[PeriodicidadReporte] WHERE [IdPeriodicidadReporte] = 4)
BEGIN
INSERT [dbo].[PeriodicidadReporte] ([IdPeriodicidadReporte], [Nombre], [Descripcion]) VALUES (4, N'Por Evento', N'Información reportada cada que ocurre algún evento')
END
GO

IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = N'IdPeriodicidadReporte' and Object_ID = Object_ID(N'[dbo].[TaxonomiaXbrl]'))
BEGIN
ALTER TABLE [dbo].[TaxonomiaXbrl] ADD [IdPeriodicidadReporte] [int] CONSTRAINT DefaultPeriodicidadTaxonomia DEFAULT 1 NOT NULL
ALTER TABLE [dbo].[TaxonomiaXbrl]  WITH CHECK ADD CONSTRAINT [FK_DocumentoInstancia_Period] FOREIGN KEY([IdPeriodicidadReporte]) REFERENCES [dbo].[PeriodicidadReporte] ([IdPeriodicidadReporte])
END
GO


UPDATE [dbo].[PeriodicidadReporte] SET [Nombre] = 'Mensual', [Descripcion] = 'Información reportada cada mes' WHERE [IdPeriodicidadReporte] = 2
GO


INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'IFRS BMV 2013','Taxonomía IFRS de la BMV 2013',2013,'http://www.bmv.com.mx/fr/ics/2012-04-01/ifrs-mx-ics-entryPoint-all',1 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/fr/ics/2012-04-01/ifrs-mx-ics-entryPoint-all' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'IFRS BMV 2015 para ICS','Taxonomía IFRS de la BMV 2015 para Empresas Comerciales y de Servicios',2015,'http://www.bmv.com.mx/taxonomy/ifrs_mx/full_ifrs_mc_mx_ics_entry_point_2014-12-05',1 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/taxonomy/ifrs_mx/full_ifrs_mc_mx_ics_entry_point_2014-12-05' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'IFRS BMV 2015 para SAPIB','Taxonomía IFRS de la BMV 2015 para Empresas de Sociedad Anónima Promotora de Inversión Bursátil',2015,'http://www.bmv.com.mx/taxonomy/ifrs_mx/full_ifrs_mc_mx_sapib_entry_point_2014-12-05',1 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/taxonomy/ifrs_mx/full_ifrs_mc_mx_sapib_entry_point_2014-12-05' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'IFRS BMV 2015 para Corto Plazo','Taxonomía IFRS de la BMV 2015 para Empresas de Corto Plazo',2015,'http://www.bmv.com.mx/taxonomy/ifrs_mx/full_ifrs_mc_mx_cp_entry_point_2014-12-05',1 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/taxonomy/ifrs_mx/full_ifrs_mc_mx_cp_entry_point_2014-12-05' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'IFRS BMV 2015 para FIBRAS','Taxonomía IFRS de la BMV 2015 para Fideicomisos de Inversión en Bienes Raíces',2015,'http://www.bmv.com.mx/taxonomy/ifrs_mx/full_ifrs_mc_mx_fibras_entry_point_2014-12-05',1 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/taxonomy/ifrs_mx/full_ifrs_mc_mx_fibras_entry_point_2014-12-05' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Fideicomisos CCD','Taxonomía Fideicomisos para CCD',2015,'http://www.bmv.com.mx/2015-06-30/ccd/full_ifrs_ccd_entry_point_2015-06-30',1 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2015-06-30/ccd/full_ifrs_ccd_entry_point_2015-06-30' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Fideicomisos Deuda','Taxonomía Fideicomisos para Deuda',2015,'http://www.bmv.com.mx/2015-06-30/deuda/full_ifrs_deuda_entry_point_2015-06-30',1 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2015-06-30/deuda/full_ifrs_deuda_entry_point_2015-06-30' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Fideicomisos Trac','Taxonomía Fideicomisos para Trac',2015,'http://www.bmv.com.mx/2015-06-30/trac/full_ifrs_trac_entry_point_2015-06-30',1 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2015-06-30/trac/full_ifrs_trac_entry_point_2015-06-30' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Anexo T','Taxonomía para Anexo T',2016,'http://www.bmv.com.mx/2016-08-22/annext_entrypoint',2 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/annext_entrypoint' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Reporte Anual - Anexo N','Reporte Anual - Anexo N',2016,'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_N_entry_point_2016-08-22',3 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_N_entry_point_2016-08-22' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Reporte Anual - Anexo NBIS','Reporte Anual - Anexo NBIS',2016,'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_NBIS_entry_point_2016-08-22',3 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_NBIS_entry_point_2016-08-22' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Reporte Anual - Anexo NBIS1','Reporte Anual - Anexo NBIS1',2016,'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_NBIS1_entry_point_2016-08-22',3 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_NBIS1_entry_point_2016-08-22' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Reporte Anual - Anexo NBIS2','Reporte Anual - Anexo NBIS2',2016,'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_NBIS2_entry_point_2016-08-22',3 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_NBIS2_entry_point_2016-08-22' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Reporte Anual - Anexo NBIS3','Reporte Anual - Anexo NBIS3',2016,'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_NBIS3_entry_point_2016-08-22',3 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_NBIS3_entry_point_2016-08-22' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Reporte Anual - Anexo NBIS4','Reporte Anual - Anexo NBIS4',2016,'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_NBIS4_entry_point_2016-08-22',3 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_NBIS4_entry_point_2016-08-22' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Reporte Anual - Anexo NBIS5','Reporte Anual - Anexo NBIS5',2016,'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_NBIS5_entry_point_2016-08-22',3 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_NBIS5_entry_point_2016-08-22' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Reporte Anual - Anexo O','Reporte Anual - Anexo O',2016,'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_O_entry_point_2016-08-22',3 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_O_entry_point_2016-08-22' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Prospecto de Colocación - Anexo H','Prospecto de Colocación - Anexo H',2016,'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_H_entry_point_2016-08-22',4 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_H_entry_point_2016-08-22' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Prospecto de Colocación - Anexo HBIS','Prospecto de Colocación - Anexo HBIS',2016,'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_HBIS_entry_point_2016-08-22',4 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_HBIS_entry_point_2016-08-22' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Prospecto de Colocación - Anexo HBIS1','Prospecto de Colocación - Anexo HBIS1',2016,'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_HBIS1_entry_point_2016-08-22',4 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_HBIS1_entry_point_2016-08-22' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Prospecto de Colocación - Anexo HBIS2','Prospecto de Colocación - Anexo HBIS2',2016,'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_HBIS2_entry_point_2016-08-22',4 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_HBIS2_entry_point_2016-08-22' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Prospecto de Colocación - Anexo HBIS3','Prospecto de Colocación - Anexo HBIS3',2016,'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_HBIS3_entry_point_2016-08-22',4 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_HBIS3_entry_point_2016-08-22' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Prospecto de Colocación - Anexo HBIS4','Prospecto de Colocación - Anexo HBIS4',2016,'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_HBIS4_entry_point_2016-08-22',4 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_HBIS4_entry_point_2016-08-22' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Prospecto de Colocación - Anexo HBIS5','Prospecto de Colocación - Anexo HBIS5',2016,'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_HBIS5_entry_point_2016-08-22',4 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_HBIS5_entry_point_2016-08-22' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Prospecto de Colocación - Anexo L','Prospecto de Colocación - Anexo L',2016,'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_L_entry_point_2016-08-22',4 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_L_entry_point_2016-08-22' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Prospecto de Colocación - Anexo I','Prospecto de Colocación - Anexo I',2016,'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_I_entry_point_2016-08-22',4 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_I_entry_point_2016-08-22' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Eventos relevantes 2016 - Emisoras','Eventos relevantes 2016 - Emisoras',2016,'http://www.bmv.com.mx/2016-08-22/rel_ev_emisoras_entrypoint',4 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/rel_ev_emisoras_entrypoint' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Eventos relevantes 2016 - Fondos de inversión','Eventos relevantes 2016 - Fondos de inversión',2016,'http://www.bmv.com.mx/2016-08-22/rel_ev_fondos_entrypoint',4 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/rel_ev_fondos_entrypoint' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'IFRS BMV 2016 para FIBRAS','Taxonomía IFRS de la BMV 2016 para Fideicomisos de Inversión en Bienes Raíces',2016,'http://www.bmv.com.mx/taxonomy/ifrs_mx/full_ifrs_mc_mx_fibras_entry_point_2016-08-22',1 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/taxonomy/ifrs_mx/full_ifrs_mc_mx_fibras_entry_point_2016-08-22' ))
INSERT INTO [dbo].[TaxonomiaXbrl] ([Nombre],[Descripcion],[Anio],[EspacioNombresPrincipal],[IdPeriodicidadReporte]) (SELECT 'Fideicomisos CCD 2016','Taxonomía Fideicomisos para CCD 2016',2016,'http://www.bmv.com.mx/2015-06-30/ccd/full_ifrs_ccd_entry_point_2016-08-22',1 WHERE NOT EXISTS (SELECT [IdTaxonomiaXbrl] FROM [dbo].[TaxonomiaXbrl] WHERE [EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2015-06-30/ccd/full_ifrs_ccd_entry_point_2016-08-22' ))
GO


INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/mx-ifrs-ics-2012-04-01/All/ifrs-mx-ics-entryPoint-all-2012-04-01.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/fr/ics/2012-04-01/ifrs-mx-ics-entryPoint-all'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/mx-ifrs-ics-2012-04-01/All/ifrs-mx-ics-entryPoint-all-2012-04-01.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/mx-ifrs-2014-12-05/full_ifrs_mc_mx_ics_entry_point_2014-12-05.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/taxonomy/ifrs_mx/full_ifrs_mc_mx_ics_entry_point_2014-12-05'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/mx-ifrs-2014-12-05/full_ifrs_mc_mx_ics_entry_point_2014-12-05.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/mx-ifrs-2014-12-05/full_ifrs_mc_mx_sapib_entry_point_2014-12-05.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/taxonomy/ifrs_mx/full_ifrs_mc_mx_sapib_entry_point_2014-12-05'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/mx-ifrs-2014-12-05/full_ifrs_mc_mx_sapib_entry_point_2014-12-05.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/mx-ifrs-2014-12-05/full_ifrs_mc_mx_cp_entry_point_2014-12-05.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/taxonomy/ifrs_mx/full_ifrs_mc_mx_cp_entry_point_2014-12-05'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/mx-ifrs-2014-12-05/full_ifrs_mc_mx_cp_entry_point_2014-12-05.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/mx-ifrs-2014-12-05/full_ifrs_mc_mx_fibras_entry_point_2014-12-05.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/taxonomy/ifrs_mx/full_ifrs_mc_mx_fibras_entry_point_2014-12-05'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/mx-ifrs-2014-12-05/full_ifrs_mc_mx_fibras_entry_point_2014-12-05.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/mx-ifrs-fid-2015-06-30/ccd/full_ifrs_ccd_entry_point_2015-06-30.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2015-06-30/ccd/full_ifrs_ccd_entry_point_2015-06-30'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/mx-ifrs-fid-2015-06-30/ccd/full_ifrs_ccd_entry_point_2015-06-30.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/mx-ifrs-fid-2015-06-30/deuda/full_ifrs_deuda_entry_point_2015-06-30.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2015-06-30/deuda/full_ifrs_deuda_entry_point_2015-06-30'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/mx-ifrs-fid-2015-06-30/deuda/full_ifrs_deuda_entry_point_2015-06-30.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/mx-ifrs-fid-2015-06-30/trac/full_ifrs_trac_entry_point_2015-06-30.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2015-06-30/trac/full_ifrs_trac_entry_point_2015-06-30'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/mx-ifrs-fid-2015-06-30/trac/full_ifrs_trac_entry_point_2015-06-30.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/anexot-2016-08-22/annext_entry_point_2016-08-22.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/annext_entrypoint'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/anexot-2016-08-22/annext_entry_point_2016-08-22.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/ar_N_entry_point_2016-08-22.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_N_entry_point_2016-08-22'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/ar_N_entry_point_2016-08-22.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/ar_NBIS_entry_point_2016-08-22.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_NBIS_entry_point_2016-08-22'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/ar_NBIS_entry_point_2016-08-22.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/ar_NBIS1_entry_point_2016-08-22.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_NBIS1_entry_point_2016-08-22'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/ar_NBIS1_entry_point_2016-08-22.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/ar_NBIS2_entry_point_2016-08-22.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_NBIS2_entry_point_2016-08-22'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/ar_NBIS2_entry_point_2016-08-22.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/ar_NBIS3_entry_point_2016-08-22.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_NBIS3_entry_point_2016-08-22'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/ar_NBIS3_entry_point_2016-08-22.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/ar_NBIS4_entry_point_2016-08-22.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_NBIS4_entry_point_2016-08-22'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/ar_NBIS4_entry_point_2016-08-22.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/ar_NBIS5_entry_point_2016-08-22.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_NBIS5_entry_point_2016-08-22'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/ar_NBIS5_entry_point_2016-08-22.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/ar_O_entry_point_2016-08-22.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/ar_O_entry_point_2016-08-22'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/ar_O_entry_point_2016-08-22.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/pros_H_entry_point_2016-08-22.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_H_entry_point_2016-08-22'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/pros_H_entry_point_2016-08-22.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/pros_HBIS_entry_point_2016-08-22.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_HBIS_entry_point_2016-08-22'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/pros_HBIS_entry_point_2016-08-22.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/pros_HBIS1_entry_point_2016-08-22.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_HBIS1_entry_point_2016-08-22'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/pros_HBIS1_entry_point_2016-08-22.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/pros_HBIS2_entry_point_2016-08-22.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_HBIS2_entry_point_2016-08-22'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/pros_HBIS2_entry_point_2016-08-22.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/pros_HBIS3_entry_point_2016-08-22.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_HBIS3_entry_point_2016-08-22'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/pros_HBIS3_entry_point_2016-08-22.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/pros_HBIS4_entry_point_2016-08-22.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_HBIS4_entry_point_2016-08-22'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/pros_HBIS4_entry_point_2016-08-22.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/pros_HBIS5_entry_point_2016-08-22.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_HBIS5_entry_point_2016-08-22'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/pros_HBIS5_entry_point_2016-08-22.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/pros_L_entry_point_2016-08-22.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_L_entry_point_2016-08-22'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/pros_L_entry_point_2016-08-22.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/pros_I_entry_point_2016-08-22.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/ar_prospectus/pros_I_entry_point_2016-08-22'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/ra-prospecto-2016-08-22/pros_I_entry_point_2016-08-22.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/eventos-relevantes-2016-08-22/rel_ev_emisoras_entry_point_2016-08-22.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/rel_ev_emisoras_entrypoint'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/eventos-relevantes-2016-08-22/rel_ev_emisoras_entry_point_2016-08-22.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/eventos-relevantes-2016-08-22/rel_ev_fondos_entry_point_2016-08-22.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2016-08-22/rel_ev_fondos_entrypoint'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/eventos-relevantes-2016-08-22/rel_ev_fondos_entry_point_2016-08-22.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/mx-ifrs-2014-12-05/full_ifrs_mc_mx_fibras_entry_point_2016-08-22.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/taxonomy/ifrs_mx/full_ifrs_mc_mx_fibras_entry_point_2016-08-22'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/mx-ifrs-2014-12-05/full_ifrs_mc_mx_fibras_entry_point_2016-08-22.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
INSERT INTO [dbo].[ArchivoTaxonomiaXbrl] ([IdTaxonomiaXbrl] ,[TipoReferencia] ,[Href] ,[Rol] ,[RolUri])(SELECT [IdTaxonomiaXbrl], 1,'http://emisnet.bmv.com.mx/taxonomy/mx-ifrs-fid-2015-06-30/ccd/full_ifrs_ccd_entry_point_2016-08-22.xsd', NULL,NULL FROM [dbo].[TaxonomiaXbrl] TAX WHERE TAX.[EspacioNombresPrincipal] = 'http://www.bmv.com.mx/2015-06-30/ccd/full_ifrs_ccd_entry_point_2016-08-22'  AND NOT EXISTS (SELECT AR.[IdArchivoTaxonomiaXbrl] FROM [ArchivoTaxonomiaXbrl] AR WHERE AR.[Href] = 'http://emisnet.bmv.com.mx/taxonomy/mx-ifrs-fid-2015-06-30/ccd/full_ifrs_ccd_entry_point_2016-08-22.xsd' AND AR.[IdTaxonomiaXbrl] = TAX.[IdTaxonomiaXbrl]))
GO