//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alerta
    {
        public long IdAlerta { get; set; }
        public string Contenido { get; set; }
        public long IdUsuario { get; set; }
        public long IdDocumentoInstancia { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool DocumentoCorrecto { get; set; }
    
        public virtual DocumentoInstancia DocumentoInstancia { get; set; }
    }
}
