//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivoAdjuntoXbrl
    {
        public long IdArchivoAdjuntoXbrl { get; set; }
        public long IdDocumentoInstancia { get; set; }
        public string IdHecho { get; set; }
        public string IdConcepto { get; set; }
        public string IdContexto { get; set; }
        public string Archivo { get; set; }
    
        public virtual DocumentoInstancia DocumentoInstancia { get; set; }
    }
}
