//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivoDocumentoInstancia
    {
        public long IdArchivoDocumentoInstancia { get; set; }
        public long IdDocumentoInstancia { get; set; }
        public Nullable<long> IdTipoArchivo { get; set; }
        public byte[] Archivo { get; set; }
    
        public virtual DocumentoInstancia DocumentoInstancia { get; set; }
        public virtual TipoArchivo TipoArchivo { get; set; }
    }
}
