//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtributoPlantillaDocumentoInstancia
    {
        public long IdAtributoPlantilla { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int Tipo { get; set; }
        public string InformacionAdicional { get; set; }
        public long IdPlantillaDocumentoInstancia { get; set; }
    
        public virtual PlantillaDocumentoInstancia PlantillaDocumentoInstancia { get; set; }
    }
}
