//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraVersionDocumento
    {
        public BitacoraVersionDocumento()
        {
            this.BitacoraDistribucionDocumento = new HashSet<BitacoraDistribucionDocumento>();
        }
    
        public long IdBitacoraVersionDocumento { get; set; }
        public long IdDocumentoInstancia { get; set; }
        public long IdVersionDocumentoInstancia { get; set; }
        public int Estatus { get; set; }
        public string MensajeError { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaUltimaModificacion { get; set; }
        public string Empresa { get; set; }
        public string Usuario { get; set; }
    
        public virtual ICollection<BitacoraDistribucionDocumento> BitacoraDistribucionDocumento { get; set; }
        public virtual DocumentoInstancia DocumentoInstancia { get; set; }
        public virtual VersionDocumentoInstancia VersionDocumentoInstancia { get; set; }
    }
}
