//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraProcesarArchivosBMV
    {
        public long IdBitacoraProcesarArchivosBMV { get; set; }
        public System.DateTime FechaHoraProcesamiento { get; set; }
        public int Estatus { get; set; }
        public string RutaOrigenArchivoEmisoras { get; set; }
        public string RutaDestinoArchivoEmisoras { get; set; }
        public string RutaOrigenArchivoFideicomisos { get; set; }
        public string RutaDestinoArchivoFideicomisos { get; set; }
        public int NumeroEmisorasReportadas { get; set; }
        public int NumeroFideicomisosReportados { get; set; }
        public string InformacionSalida { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
    }
}
