//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaAnalisisEntidad
    {
        public long IdConsultaAnalisisEntidad { get; set; }
        public long IdConsultaAnalisis { get; set; }
        public Nullable<long> idEmpresa { get; set; }
        public string NombreEntidad { get; set; }
    
        public virtual ConsultaAnalisis ConsultaAnalisis { get; set; }
    }
}
