//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaAnalisisPeriodo
    {
        public long IdConsultaAnalisisPeriodo { get; set; }
        public long IdConsultaAnalisis { get; set; }
        public string Periodo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<int> TipoPeriodo { get; set; }
        public Nullable<int> Anio { get; set; }
        public string Trimestre { get; set; }
    
        public virtual ConsultaAnalisis ConsultaAnalisis { get; set; }
    }
}
