//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaRepositorio
    {
        public long IdConsultaRepositorio { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Consulta { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<long> IdUsuario { get; set; }
        public bool Publica { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
