//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contexto
    {
        public Contexto()
        {
            this.Hecho = new HashSet<Hecho>();
        }
    
        public long IdContexto { get; set; }
        public string Nombre { get; set; }
        public int TipoContexto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<bool> PorSiempre { get; set; }
        public string Escenario { get; set; }
        public Nullable<long> IdDocumentoInstancia { get; set; }
        public string EsquemaEntidad { get; set; }
        public string IdentificadorEntidad { get; set; }
        public string Segmento { get; set; }
    
        public virtual DocumentoInstancia DocumentoInstancia { get; set; }
        public virtual ICollection<Hecho> Hecho { get; set; }
    }
}
