//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestinatarioNotificacion
    {
        public long IdDestinatarioNotificacion { get; set; }
        public long IdListaNotificacion { get; set; }
        public string Nombre { get; set; }
        public string CorreoElectronico { get; set; }
    
        public virtual ListaNotificacion ListaNotificacion { get; set; }
    }
}
