//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoInstancia
    {
        public DocumentoInstancia()
        {
            this.Alerta = new HashSet<Alerta>();
            this.BitacoraVersionDocumento = new HashSet<BitacoraVersionDocumento>();
            this.Contexto = new HashSet<Contexto>();
            this.DtsDocumentoInstancia = new HashSet<DtsDocumentoInstancia>();
            this.Hecho = new HashSet<Hecho>();
            this.NotaAlPie = new HashSet<NotaAlPie>();
            this.Unidad = new HashSet<Unidad>();
            this.UsuarioDocumentoInstancia = new HashSet<UsuarioDocumentoInstancia>();
            this.VersionDocumentoInstancia = new HashSet<VersionDocumentoInstancia>();
            this.ArchivoDocumentoInstancia = new HashSet<ArchivoDocumentoInstancia>();
            this.ArchivoAdjuntoXbrl = new HashSet<ArchivoAdjuntoXbrl>();
        }
    
        public long IdDocumentoInstancia { get; set; }
        public string Titulo { get; set; }
        public string RutaArchivo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<long> IdEmpresa { get; set; }
        public bool EsCorrecto { get; set; }
        public bool Bloqueado { get; set; }
        public Nullable<long> IdUsuarioBloqueo { get; set; }
        public Nullable<long> IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> FechaUltMod { get; set; }
        public Nullable<int> UltimaVersion { get; set; }
        public string GruposContextosEquivalentes { get; set; }
        public string ParametrosConfiguracion { get; set; }
        public string EspacioNombresPrincipal { get; set; }
        public string ClaveEmisora { get; set; }
        public Nullable<int> Anio { get; set; }
        public string Trimestre { get; set; }
        public Nullable<long> IdEmpresaEnvio { get; set; }
        public string NumFideicomiso { get; set; }
        public Nullable<System.DateTime> FechaReporte { get; set; }
    
        public virtual ICollection<Alerta> Alerta { get; set; }
        public virtual ICollection<BitacoraVersionDocumento> BitacoraVersionDocumento { get; set; }
        public virtual ICollection<Contexto> Contexto { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<DtsDocumentoInstancia> DtsDocumentoInstancia { get; set; }
        public virtual ICollection<Hecho> Hecho { get; set; }
        public virtual ICollection<NotaAlPie> NotaAlPie { get; set; }
        public virtual ICollection<Unidad> Unidad { get; set; }
        public virtual ICollection<UsuarioDocumentoInstancia> UsuarioDocumentoInstancia { get; set; }
        public virtual ICollection<VersionDocumentoInstancia> VersionDocumentoInstancia { get; set; }
        public virtual ICollection<ArchivoDocumentoInstancia> ArchivoDocumentoInstancia { get; set; }
        public virtual Empresa Empresa1 { get; set; }
        public virtual ICollection<ArchivoAdjuntoXbrl> ArchivoAdjuntoXbrl { get; set; }
    }
}
