//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtsDocumentoInstancia
    {
        public long IdDtsDocumentoInstancia { get; set; }
        public long IdDocumentoInstancia { get; set; }
        public string Href { get; set; }
        public string Rol { get; set; }
        public string RolUri { get; set; }
        public int TipoReferencia { get; set; }
    
        public virtual DocumentoInstancia DocumentoInstancia { get; set; }
    }
}
