//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.DocumentoInstancia = new HashSet<DocumentoInstancia>();
            this.Fideicomiso = new HashSet<Fideicomiso>();
            this.GrupoUsuarios = new HashSet<GrupoUsuarios>();
            this.RegistroAuditoria = new HashSet<RegistroAuditoria>();
            this.RelacionEmpresas = new HashSet<RelacionEmpresas>();
            this.RelacionEmpresas1 = new HashSet<RelacionEmpresas>();
            this.Rol = new HashSet<Rol>();
            this.UsuarioEmpresa = new HashSet<UsuarioEmpresa>();
            this.VersionDocumentoInstancia = new HashSet<VersionDocumentoInstancia>();
            this.GrupoEmpresa1 = new HashSet<GrupoEmpresa>();
            this.TipoEmpresa = new HashSet<TipoEmpresa>();
            this.DocumentoInstancia1 = new HashSet<DocumentoInstancia>();
            this.RepresentanteComunFideciomiso = new HashSet<RepresentanteComunFideciomiso>();
        }
    
        public long IdEmpresa { get; set; }
        public string RazonSocial { get; set; }
        public string NombreCorto { get; set; }
        public string RFC { get; set; }
        public string DomicilioFiscal { get; set; }
        public Nullable<bool> Borrado { get; set; }
        public string GrupoEmpresa { get; set; }
        public Nullable<bool> Fideicomitente { get; set; }
        public string AliasClaveCotizacion { get; set; }
        public Nullable<bool> RepresentanteComun { get; set; }
    
        public virtual ICollection<DocumentoInstancia> DocumentoInstancia { get; set; }
        public virtual ICollection<Fideicomiso> Fideicomiso { get; set; }
        public virtual ICollection<GrupoUsuarios> GrupoUsuarios { get; set; }
        public virtual ICollection<RegistroAuditoria> RegistroAuditoria { get; set; }
        public virtual ICollection<RelacionEmpresas> RelacionEmpresas { get; set; }
        public virtual ICollection<RelacionEmpresas> RelacionEmpresas1 { get; set; }
        public virtual ICollection<Rol> Rol { get; set; }
        public virtual ICollection<UsuarioEmpresa> UsuarioEmpresa { get; set; }
        public virtual ICollection<VersionDocumentoInstancia> VersionDocumentoInstancia { get; set; }
        public virtual ICollection<GrupoEmpresa> GrupoEmpresa1 { get; set; }
        public virtual ICollection<TipoEmpresa> TipoEmpresa { get; set; }
        public virtual ICollection<DocumentoInstancia> DocumentoInstancia1 { get; set; }
        public virtual ICollection<RepresentanteComunFideciomiso> RepresentanteComunFideciomiso { get; set; }
    }
}
