//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entidad
    {
        public Entidad()
        {
            this.Contexto = new HashSet<Contexto>();
        }
    
        public long IdEntidad { get; set; }
        public string Identificador { get; set; }
        public string Esquema { get; set; }
        public string Segmento { get; set; }
        public string IdRef { get; set; }
    
        public virtual ICollection<Contexto> Contexto { get; set; }
    }
}
