//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facultad
    {
        public Facultad()
        {
            this.RolFacultad = new HashSet<RolFacultad>();
        }
    
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public long IdCategoriaFacultad { get; set; }
        public bool Borrado { get; set; }
        public long IdFacultad { get; set; }
    
        public virtual CategoriaFacultad CategoriaFacultad { get; set; }
        public virtual ICollection<RolFacultad> RolFacultad { get; set; }
    }
}
