//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoUsuariosRol
    {
        public long IdGrupoUsuariosRol { get; set; }
        public long IdGrupoUsuario { get; set; }
        public long IdRol { get; set; }
    
        public virtual GrupoUsuarios GrupoUsuarios { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
