//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoUsuarios
    {
        public GrupoUsuarios()
        {
            this.GrupoUsuariosRol = new HashSet<GrupoUsuariosRol>();
            this.UsuarioGrupo = new HashSet<UsuarioGrupo>();
        }
    
        public long IdGrupoUsuarios { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public long IdEmpresa { get; set; }
        public Nullable<bool> Borrado { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<GrupoUsuariosRol> GrupoUsuariosRol { get; set; }
        public virtual ICollection<UsuarioGrupo> UsuarioGrupo { get; set; }
    }
}
