//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodicidadReporte
    {
        public PeriodicidadReporte()
        {
            this.TaxonomiaXbrl = new HashSet<TaxonomiaXbrl>();
        }
    
        public int IdPeriodicidadReporte { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<TaxonomiaXbrl> TaxonomiaXbrl { get; set; }
    }
}
