//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantillaDocumentoInstancia
    {
        public PlantillaDocumentoInstancia()
        {
            this.DocumentoInstancia = new HashSet<DocumentoInstancia>();
            this.AtributoPlantillaDocumentoInstancia = new HashSet<AtributoPlantillaDocumentoInstancia>();
        }
    
        public long IdPlantillaDocumentoInstancia { get; set; }
        public string Nombre { get; set; }
        public string Ruta { get; set; }
        public Nullable<long> IdTaxonomiaXbrl { get; set; }
        public string InformacionAdicional { get; set; }
    
        public virtual ICollection<DocumentoInstancia> DocumentoInstancia { get; set; }
        public virtual TaxonomiaXbrl TaxonomiaXbrl { get; set; }
        public virtual ICollection<AtributoPlantillaDocumentoInstancia> AtributoPlantillaDocumentoInstancia { get; set; }
    }
}
