//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroAuditoria
    {
        public long IdRegistroAuditoria { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<long> IdUsuario { get; set; }
        public long IdModulo { get; set; }
        public long IdAccionAuditable { get; set; }
        public string Registro { get; set; }
        public Nullable<long> IdEmpresa { get; set; }
    
        public virtual AccionAuditable AccionAuditable { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Modulo Modulo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
