//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepresentanteComunFideciomiso
    {
        public long IdTipoRelacionEmpresa { get; set; }
        public long IdEmpresaPrimaria { get; set; }
        public long IdEmpresaSecundaria { get; set; }
        public string Parametros { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Empresa EmpresaSecundaria { get; set; }
        public virtual TipoRelacionEmpresa TipoRelacionEmpresa { get; set; }
    }
}
