//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDato
    {
        public TipoDato()
        {
            this.Hecho = new HashSet<Hecho>();
        }
    
        public long IdTipoDato { get; set; }
        public string Nombre { get; set; }
        public bool EsNumerico { get; set; }
        public bool EsFraccion { get; set; }
        public string NombreXbrl { get; set; }
    
        public virtual ICollection<Hecho> Hecho { get; set; }
    }
}
