//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoArchivo
    {
        public TipoArchivo()
        {
            this.ArchivoDocumentoInstancia = new HashSet<ArchivoDocumentoInstancia>();
        }
    
        public long IdTipoArchivo { get; set; }
        public string Extension { get; set; }
        public string TipoArchivo1 { get; set; }
    
        public virtual ICollection<ArchivoDocumentoInstancia> ArchivoDocumentoInstancia { get; set; }
    }
}
