//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unidad
    {
        public Unidad()
        {
            this.Hecho = new HashSet<Hecho>();
        }
    
        public long IdUnidad { get; set; }
        public string Medida { get; set; }
        public string Numerador { get; set; }
        public string Denominador { get; set; }
        public bool EsFraccion { get; set; }
        public Nullable<long> IdDocumentoInstancia { get; set; }
        public string IdRef { get; set; }
    
        public virtual DocumentoInstancia DocumentoInstancia { get; set; }
        public virtual ICollection<Hecho> Hecho { get; set; }
    }
}
