//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioGrupo
    {
        public long IdUsuarioGrupo { get; set; }
        public long IdUsuario { get; set; }
        public long IdGrupoUsuarios { get; set; }
    
        public virtual GrupoUsuarios GrupoUsuarios { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
