//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaxXBRLCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersionDocumentoInstancia
    {
        public VersionDocumentoInstancia()
        {
            this.BitacoraVersionDocumento = new HashSet<BitacoraVersionDocumento>();
        }
    
        public long IdVersionDocumentoInstancia { get; set; }
        public long IdDocumentoInstancia { get; set; }
        public int Version { get; set; }
        public Nullable<long> IdUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Comentarios { get; set; }
        public string Datos { get; set; }
        public Nullable<long> IdEmpresa { get; set; }
        public bool EsCorrecto { get; set; }
    
        public virtual ICollection<BitacoraVersionDocumento> BitacoraVersionDocumento { get; set; }
        public virtual DocumentoInstancia DocumentoInstancia { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
